#! /usr/bin/env zsh

local i

if [[ $# == 0 ]]; then
    i=1
else
    i="$1"
fi

# 127.0.0.1 already exists, so start with 127.0.0.2 and add the given number of aliases
i=$(( i + 1 ))

set -x
for n ({2..$(( $i ))}); do
    ifconfig lo0 alias 127.0.0."$n" up
done
set +x
