#! /usr/bin/env zsh

local i

if [[ $# == 0 ]]; then
    i=1
else
    i="$1"
fi

# 172.0.0.1 already exists
i=$(( i + 1 ))

set -x
for n ({2..$(( $i ))})
do
    ifconfig lo0 alias 127.0.0."$n"
done
set +x
